config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # CREATE
  # get the form for the info
  get 'tasks/new', to: 'tasks#new'

  # add task (CREATE)
  post 'tasks', to: 'tasks#create'

  # SHOW
  # show all tasks
  get 'tasks', to: 'tasks#index'

  # show one task
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  # UPDATE
  # edit a task
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'

  # update the task
  patch 'tasks/:id', to: 'tasks#update'

  # DELETE
  # delete
  delete 'tasks/:id', to: 'tasks#destroy', as: 'tasks_destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    # this has the form to get the information
    @task = Task.new
  end

  def create
    @task = Task.create(name: params[:task][:name])
    redirect_to tasks_path
  end

  def edit
    # this has the form to get the information, nothing to do with data
    @task = Task.find(params[:id])

  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @restaurant = Task.destroy(params[:id])
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1 class="text-center">My Tasks</h1>
<div class="container">
  <div class="row">
    <p><% @tasks.each do |task| %></p>
      <div class="col-lg-8">
        <table>
        <tr>
        <td><%= "#{task.name} - Done? #{task.done}" %></td>
        </tr>
        </table>
        <%= link_to "Show", task_path(task) %>
        <%= link_to "Edit", edit_task_path(task) %>
        <%= link_to "Delete", tasks_destroy_path(task), method: :delete %>
      <% end %>
      <hr>
      <%= link_to "Create new Task", tasks_new_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>Enter New Task</h1>

<!-- app/views/restaurants/new.html.erb -->
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Show Details</h1>

<%= @task.name %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>